# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

steps:
- name: gcr.io/cloud-builders/git
  id: update-submodules
  args: ['submodule', 'update', '--init']

- name: gcr.io/cloud-builders/git
  id: recreate-tag
  args: ['tag', '$_TAG']

- name: gcr.io/cloud-devrel-public-resources/java11
  id: package-deploy-mvn-registry
  waitFor:
    - update-submodules
    - recreate-tag
  entrypoint: bash
  args:
    - '-c'
    - 'source ci/common.sh && retry_with_backoff 3 10 ./mvnw -U -s mvn-settings.xml -Drevision=`git describe --tags --always --dirty=-dirty` deploy'
  secretEnv: ['GITHUB_TOKEN']

- name: gcr.io/cloud-devrel-public-resources/java11
  id: ingestion-container-build
  waitFor:
    - update-submodules
    - recreate-tag
  entrypoint: bash
  args:
    - '-c'
    - 'source ci/common.sh && retry_with_backoff 3 10 ./mvnw -Pingestion-container-build -Dcontainer-version=`git describe --tags --always --dirty=-dirty` -Dcontainer_registry_tag_prefix="gcr.io/enpa-infra" package'

- name: gcr.io/cloud-devrel-public-resources/java11
  id: deletion-container-build
  waitFor:
    - update-submodules
    - recreate-tag
  entrypoint: bash
  args:
    - '-c'
    - 'source ci/common.sh && retry_with_backoff 3 10 ./mvnw -Pdeletion-container-build -Dcontainer-version=`git describe --tags --always --dirty=-dirty` -Dcontainer_registry_tag_prefix="gcr.io/enpa-infra" package'

- name: gcr.io/google.com/cloudsdktool/cloud-sdk:alpine
  id: flex-template-generator-and-uploader
  waitFor:
    - ingestion-container-build
    - deletion-container-build
  args:
    - "./ci/generate-templates.sh"
  env:
    - PROJECT_ID=$PROJECT_ID
substitutions:
  _DEFAULT: '${SHORT_SHA}-SNAPSHOT'
  _TAG: ${TAG_NAME:-$_DEFAULT} #default value will be SHORT_SHA-SNAPSHOT
secrets:
  - kmsKeyName: projects/enpa-infra/locations/global/keyRings/cloudbuild-keyring/cryptoKeys/cloudbuild
    secretEnv:
      GITHUB_TOKEN: 'CiQAzNSb40phOg8+Rtn21yuiJuqJA3CKm5YWgigMwpA5lsM42NgSUQA/9gK92tb89IansK/cTpYuAJpf9PUZ7Lvse94FqFmk/mVULLISsoNr6+39npTZAG2el7cRQ22LozB5lwE9dZGywalT7xHxs46+nywy/ix8Qg=='