on:
  push:
    branches:
    - main
  pull_request:
name: ci
jobs:
  units:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: textbook/git-checkout-submodule-action@master
    - uses: actions/setup-java@v1
      with:
        java-version: 11
    - run: java -version
    - run: ci/build.sh
      env:
        JOB_TYPE: test
  dependencies:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: textbook/git-checkout-submodule-action@master
    - uses: actions/setup-java@v1
      with:
        java-version: 11
    - run: java -version
    - run: ci/dependencies.sh
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: textbook/git-checkout-submodule-action@master
    - uses: actions/setup-java@v1
      with:
        java-version: 11
    - run: java -version
    - run: ci/build.sh
      env:
        JOB_TYPE: lint